[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common={path = "../common"}
dotenvy = "0.15.7"
log="0.4.20"
log4rs="1.2.0"
env_logger="0.10.0"
bincode="1.3.3"
