[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
userinfo-web={path= "../userinfo-web" }
socket={path = "../socket"}
common={path = "../common"}
bincode="1.3.3"
log="0.4.17"
env_logger="0.10.0"
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15.7"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
